// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { UserAgent } from '@aws-sdk/types';

export const USER_AGENT_STRING: UserAgent = [[<string>process.env.USER_AGENT_STRING]];
export const REGION: string = process.env.AWS_REGION || '';
export const SECURITY_LAKE_ACCOUNT_ID = process.env.SECURITY_LAKE_ACCOUNT_ID!;
export const SECURITY_LAKE_VPC_TABLE_NAME = process.env.SECURITY_LAKE_VPC_TABLE_NAME!;
export const SECURITY_LAKE_CLOUDTRAIL_TABLE_NAME = process.env.SECURITY_LAKE_CLOUDTRAIL_TABLE_NAME!;
export const SECURITY_LAKE_SECURITY_HUB_TABLE_NAME = process.env.SECURITY_LAKE_SECURITY_HUB_TABLE_NAME!;
export const SECURITY_LAKE_APP_FABRIC_TABLE_NAME = process.env.SECURITY_LAKE_APP_FABRIC_TABLE_NAME!;
export const SECURITY_LAKE_DATABASE_NAME = process.env.SECURITY_LAKE_DATABASE_NAME!;
export const RESOURCE_LINK_DATABASE_NAME = process.env.RESOURCE_LINK_DATABASE_NAME!;
export const CURRENT_ACCOUNT_ID = process.env.CURRENT_ACCOUNT_ID!;
export const QUICKSIGHT_SERVICE_LINKED_ROLE = process.env.QUICKSIGHT_SERVICE_ROLE!;
export const QUICKSIGHT_ADMIN_USER = process.env.QUICKSIGHT_ADMIN_USER!;
export const LAMBDA_EXECUTION_ROLE_ARN = process.env.LAMBDA_EXECUTION_ROLE_ARN!;
export const QUICKSIGHT_ADMIN_USER_GROUP_ARN = process.env.QUICKSIGHT_ADMIN_USER_GROUP_ARN!;
export const QUICKSIGHT_READ_USER_GROUP_ARN = process.env.QUICKSIGHT_READ_USER_GROUP_ARN!;
export const LIST_OF_PRINCIPALS_FOR_DATA_LAKE = [
  QUICKSIGHT_SERVICE_LINKED_ROLE,
  QUICKSIGHT_ADMIN_USER,
  QUICKSIGHT_ADMIN_USER_GROUP_ARN,
  QUICKSIGHT_READ_USER_GROUP_ARN,
];
export const DELAY_IN_SECONDS_FOR_RATE_LIMITING = process.env.DELAY_IN_SECONDS_FOR_RATE_LIMITING!;
export const LIST_OF_TABLE_NAMES_FOR_DASHBOARD = [
  SECURITY_LAKE_VPC_TABLE_NAME,
  SECURITY_LAKE_CLOUDTRAIL_TABLE_NAME,
  SECURITY_LAKE_SECURITY_HUB_TABLE_NAME,
  SECURITY_LAKE_APP_FABRIC_TABLE_NAME,
];
export const LIST_OF_RESOURCE_LINKS = [
  SECURITY_LAKE_VPC_TABLE_NAME,
  SECURITY_LAKE_CLOUDTRAIL_TABLE_NAME,
  SECURITY_LAKE_SECURITY_HUB_TABLE_NAME,
  SECURITY_LAKE_APP_FABRIC_TABLE_NAME,
];
